apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    name: my-web-app
    app: db-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30004
  selector:
    name: my-web-app
    app: db-app
